# SPDX-FileCopyrightText: Copyright (c) 2026 The Newton Developers
# SPDX-License-Identifier: Apache-2.0

"""Public scene description API."""

from .compiler import CompiledScene, SceneCompilerNewton
from .executor import SceneExecutorLocal
from .model import (
    SCHEMA_VERSION,
    Action,
    ActionEmit,
    ActionForce,
    ActionImpulse,
    ActionTransform,
    Camera,
    ClothSolverSettings,
    Constraint,
    ConstraintDistance,
    ConstraintFixedPoint,
    CouplingSettings,
    Field,
    FieldRadial,
    FieldUniform,
    FluidEmitter,
    FluidSolverSettings,
    Keyframe,
    Light,
    Material,
    MaterialPhysical,
    MaterialVisual,
    ObjectCloth,
    ObjectContainer,
    ObjectFluid,
    ObjectRigid,
    RenderSettings,
    RigidSolverSettings,
    Scene,
    SceneObject,
    ShapePrimitive,
    SimulationSettings,
    Transform,
    VertexSelector,
)
from .store import SceneStore
from .telemetry import (
    BodyTelemetry,
    ClothTelemetry,
    ContactTelemetry,
    FluidTelemetry,
    FrameTelemetry,
    SimulationTelemetry,
    SolverTelemetry,
)
from .validation import SceneDiagnostic, estimate_resources, select_pipeline, validate_scene

__all__ = [
    "SCHEMA_VERSION",
    "Action",
    "ActionEmit",
    "ActionForce",
    "ActionImpulse",
    "ActionTransform",
    "BodyTelemetry",
    "Camera",
    "ClothSolverSettings",
    "ClothTelemetry",
    "CompiledScene",
    "Constraint",
    "ConstraintDistance",
    "ConstraintFixedPoint",
    "ContactTelemetry",
    "CouplingSettings",
    "Field",
    "FieldRadial",
    "FieldUniform",
    "FluidEmitter",
    "FluidSolverSettings",
    "FluidTelemetry",
    "FrameTelemetry",
    "Keyframe",
    "Light",
    "Material",
    "MaterialPhysical",
    "MaterialVisual",
    "ObjectCloth",
    "ObjectContainer",
    "ObjectFluid",
    "ObjectRigid",
    "RenderSettings",
    "RigidSolverSettings",
    "Scene",
    "SceneCompilerNewton",
    "SceneDiagnostic",
    "SceneExecutorLocal",
    "SceneObject",
    "SceneStore",
    "ShapePrimitive",
    "SimulationSettings",
    "SimulationTelemetry",
    "SolverTelemetry",
    "Transform",
    "VertexSelector",
    "estimate_resources",
    "select_pipeline",
    "validate_scene",
]
