# SPDX-FileCopyrightText: Copyright (c) 2026 The Newton Developers
# SPDX-License-Identifier: Apache-2.0

"""Public scene description API."""

from .compiler import CompiledScene, SceneCompilerNewton
from .executor import SceneExecutorLocal
from .model import (
    SCHEMA_VERSION,
    Action,
    ActionEmit,
    ActionForce,
    ActionImpulse,
    ActionTransform,
    Camera,
    Constraint,
    ConstraintDistance,
    ConstraintFixedPoint,
    Field,
    FieldRadial,
    FieldUniform,
    FluidEmitter,
    Keyframe,
    Light,
    Material,
    MaterialPhysical,
    MaterialVisual,
    ObjectCloth,
    ObjectContainer,
    ObjectFluid,
    ObjectRigid,
    RenderSettings,
    Scene,
    SceneObject,
    ShapePrimitive,
    SimulationSettings,
    Transform,
    VertexSelector,
)
from .store import SceneStore
from .validation import SceneDiagnostic, estimate_resources, select_pipeline, validate_scene

__all__ = [
    "SCHEMA_VERSION",
    "Action",
    "ActionEmit",
    "ActionForce",
    "ActionImpulse",
    "ActionTransform",
    "Camera",
    "CompiledScene",
    "Constraint",
    "ConstraintDistance",
    "ConstraintFixedPoint",
    "Field",
    "FieldRadial",
    "FieldUniform",
    "FluidEmitter",
    "Keyframe",
    "Light",
    "Material",
    "MaterialPhysical",
    "MaterialVisual",
    "ObjectCloth",
    "ObjectContainer",
    "ObjectFluid",
    "ObjectRigid",
    "RenderSettings",
    "Scene",
    "SceneCompilerNewton",
    "SceneDiagnostic",
    "SceneExecutorLocal",
    "SceneObject",
    "SceneStore",
    "ShapePrimitive",
    "SimulationSettings",
    "Transform",
    "VertexSelector",
    "estimate_resources",
    "select_pipeline",
    "validate_scene",
]
